# Generated by Django 2.2.7 on 2019-11-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191114_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='correo',
        ),
    ]
