# Generated by Django 2.2.7 on 2019-11-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_estado_visita', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('nro', models.IntegerField()),
                ('comuna', models.CharField(max_length=30)),
                ('fono_residencial', models.IntegerField()),
                ('direccion_correo_electronico', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Ruta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observaciones', models.CharField(max_length=300)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.Propietario')),
                ('estado_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.Estado_Visita')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.Ruta')),
            ],
        ),
    ]
